-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_area_texts (
  scope_kind text NOT NULL CHECK (scope_kind = 'bundesland'::text),
  scope_key text NOT NULL,
  section_key text NOT NULL,
  text_type text NOT NULL DEFAULT 'general'::text CHECK (text_type = ANY (ARRAY['general'::text, 'individual'::text])),
  raw_content text NOT NULL DEFAULT ''::text,
  optimized_content text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'approved'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text])),
  source_snapshot_hash text,
  source_last_updated timestamp with time zone,
  updated_by text,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_area_texts_pkey PRIMARY KEY (scope_kind, scope_key, section_key)
);
CREATE TABLE public.admin_area_text_i18n_entries (
  scope_kind text NOT NULL CHECK (scope_kind = ANY (ARRAY['bundesland'::text, 'kreis'::text, 'ortslage'::text])),
  scope_key text NOT NULL,
  section_key text NOT NULL,
  locale text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'internal'::text, 'live'::text])),
  value_text text NOT NULL DEFAULT ''::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_area_text_i18n_entries_pkey PRIMARY KEY (scope_kind, scope_key, section_key, locale)
);
CREATE TABLE public.admin_area_text_i18n_meta (
  scope_kind text NOT NULL CHECK (scope_kind = ANY (ARRAY['bundesland'::text, 'kreis'::text, 'ortslage'::text])),
  scope_key text NOT NULL,
  section_key text NOT NULL,
  locale text NOT NULL,
  source_locale text NOT NULL DEFAULT 'de'::text,
  source_snapshot_hash text,
  source_updated_at timestamp with time zone,
  translation_origin text NOT NULL DEFAULT 'manual'::text CHECK (translation_origin = ANY (ARRAY['manual'::text, 'ai'::text, 'sync_copy_all'::text, 'sync_fill_missing'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_area_text_i18n_meta_pkey PRIMARY KEY (scope_kind, scope_key, section_key, locale)
);
CREATE TABLE public.market_explanation_faq_entries (
  tab_id text NOT NULL CHECK (tab_id = ANY (ARRAY['uebersicht'::text, 'immobilienpreise'::text, 'mietpreise'::text, 'mietrendite'::text, 'wohnmarktsituation'::text, 'grundstueckspreise'::text, 'wohnlagencheck'::text, 'wirtschaft'::text])),
  item_id text NOT NULL,
  locale text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'internal'::text, 'live'::text])),
  question text NOT NULL DEFAULT ''::text,
  answer text NOT NULL DEFAULT ''::text,
  sort_order integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT market_explanation_faq_entries_pkey PRIMARY KEY (tab_id, item_id, locale)
);
CREATE TABLE public.market_explanation_faq_i18n_meta (
  tab_id text NOT NULL CHECK (tab_id = ANY (ARRAY['uebersicht'::text, 'immobilienpreise'::text, 'mietpreise'::text, 'mietrendite'::text, 'wohnmarktsituation'::text, 'grundstueckspreise'::text, 'wohnlagencheck'::text, 'wirtschaft'::text])),
  item_id text NOT NULL,
  locale text NOT NULL,
  source_locale text NOT NULL DEFAULT 'de'::text,
  source_snapshot_hash text,
  source_updated_at timestamp with time zone,
  translation_origin text NOT NULL DEFAULT 'manual'::text CHECK (translation_origin = ANY (ARRAY['manual'::text, 'ai'::text, 'sync_copy_all'::text, 'sync_fill_missing'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT market_explanation_faq_i18n_meta_pkey PRIMARY KEY (tab_id, item_id, locale)
);
CREATE TABLE public.admin_users (
  auth_user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin_super'::text, 'admin_ops'::text, 'admin_billing'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (auth_user_id),
  CONSTRAINT admin_users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.areas (
  id text NOT NULL,
  name text NOT NULL,
  type text,
  parent_id text,
  slug text,
  parent_slug text,
  bundesland_slug text,
  CONSTRAINT areas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.billing_feature_catalog (
  code text NOT NULL,
  label text NOT NULL,
  note text,
  billing_unit text NOT NULL DEFAULT 'pro Monat'::text,
  default_enabled boolean NOT NULL DEFAULT false,
  default_monthly_price_eur numeric NOT NULL DEFAULT 0.00 CHECK (default_monthly_price_eur >= 0::numeric),
  sort_order integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_feature_catalog_pkey PRIMARY KEY (code)
);
CREATE TABLE public.billing_global_defaults (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  portal_base_price_eur numeric NOT NULL DEFAULT 50.00 CHECK (portal_base_price_eur >= 0::numeric),
  portal_ortslage_price_eur numeric NOT NULL DEFAULT 1.00 CHECK (portal_ortslage_price_eur >= 0::numeric),
  portal_export_ortslage_price_eur numeric NOT NULL DEFAULT 1.00 CHECK (portal_export_ortslage_price_eur >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billing_global_defaults_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_raw_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  title text,
  status text,
  source_updated_at timestamp with time zone,
  normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sync_status text NOT NULL DEFAULT 'ok'::text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_raw_references_pkey PRIMARY KEY (id),
  CONSTRAINT crm_raw_references_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.crm_raw_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  title text,
  status text,
  source_updated_at timestamp with time zone,
  normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sync_status text NOT NULL DEFAULT 'ok'::text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_raw_requests_pkey PRIMARY KEY (id),
  CONSTRAINT crm_raw_requests_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.data_value_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid,
  area_id text,
  is_active boolean DEFAULT true,
  last_update timestamp with time zone DEFAULT now(),
  standortfaktoren jsonb DEFAULT '{"bildung": 1, "gesundheit": 1, "mobilitaet": 1, "naherholung": 1, "arbeitsplatz": 1, "nahversorgung": 1, "lebenserhaltungskosten": 1}'::jsonb,
  immobilienmarkt_trend jsonb DEFAULT '{"mietmarkt": 1, "immobilienmarkt": 1}'::jsonb,
  kauf_haus jsonb DEFAULT '{"f01": 1, "f02": 1, "f03": 1, "f04": 1, "f05": 1, "f06": 1}'::jsonb,
  kauf_wohnung jsonb DEFAULT '{"f01": 1, "f02": 1, "f03": 1, "f04": 1, "f05": 1, "f06": 1}'::jsonb,
  kauf_grundstueck jsonb DEFAULT '{"f01": 1, "f02": 1, "f03": 1, "f04": 1, "f05": 1, "f06": 1}'::jsonb,
  miete_haus jsonb DEFAULT '{"f01": 1, "f02": 1, "f03": 1, "f04": 1, "f05": 1, "f06": 1}'::jsonb,
  miete_wohnung jsonb DEFAULT '{"f01": 1, "f02": 1, "f03": 1, "f04": 1, "f05": 1, "f06": 1}'::jsonb,
  rendite jsonb DEFAULT '{"mietrendite_efh": 1, "mietrendite_etw": 1, "mietrendite_mfh": 1, "kaufpreisfaktor_efh": 1, "kaufpreisfaktor_etw": 1, "kaufpreisfaktor_mfh": 1}'::jsonb,
  CONSTRAINT data_value_settings_pkey PRIMARY KEY (id),
  CONSTRAINT data_value_settings_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES public.partners(id),
  CONSTRAINT data_value_settings_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.integration_sync_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL,
  partner_id uuid NOT NULL,
  kind text NOT NULL,
  provider text NOT NULL,
  resource text NOT NULL,
  mode text,
  triggered_by text NOT NULL,
  trigger_user_id uuid,
  sync_job_id text,
  trace_id text,
  status text NOT NULL DEFAULT 'running'::text,
  step text,
  message text,
  error text,
  error_class text,
  request_count integer,
  pages_fetched integer,
  raw_offers_count integer,
  offers_count integer,
  references_count integer,
  requests_count integer,
  deactivated_raw_offers integer,
  deactivated_offers integer,
  safety_limited boolean NOT NULL DEFAULT false,
  log jsonb,
  notes jsonb,
  result_json jsonb,
  metadata jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  heartbeat_at timestamp with time zone,
  deadline_at timestamp with time zone,
  cancel_requested boolean NOT NULL DEFAULT false,
  finished_at timestamp with time zone,
  duration_ms integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT integration_sync_runs_pkey PRIMARY KEY (id),
  CONSTRAINT integration_sync_runs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.partner_integrations(id),
  CONSTRAINT integration_sync_runs_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.llm_fx_monthly_rates (
  month_start date NOT NULL,
  from_currency text NOT NULL,
  to_currency text NOT NULL,
  rate numeric NOT NULL,
  source text,
  is_locked boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT llm_fx_monthly_rates_pkey PRIMARY KEY (month_start, from_currency, to_currency)
);
CREATE TABLE public.llm_global_config (
  id boolean NOT NULL DEFAULT true,
  central_enabled boolean NOT NULL DEFAULT true,
  monthly_token_budget bigint,
  monthly_cost_budget_eur numeric,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT llm_global_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.llm_global_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider text NOT NULL,
  model text NOT NULL,
  base_url text NOT NULL,
  auth_type text NOT NULL DEFAULT 'api_key'::text,
  auth_config jsonb,
  priority integer NOT NULL DEFAULT 100,
  is_active boolean NOT NULL DEFAULT true,
  temperature numeric,
  max_tokens integer,
  input_cost_eur_per_1k numeric,
  output_cost_eur_per_1k numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  price_source text,
  price_source_url text,
  price_updated_at timestamp with time zone,
  price_source_url_override text,
  display_label text,
  hint text,
  badges jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(badges) = 'array'::text),
  recommended boolean NOT NULL DEFAULT false,
  CONSTRAINT llm_global_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.llm_partner_budget_overrides (
  partner_id uuid NOT NULL,
  monthly_token_budget bigint,
  monthly_cost_budget_eur numeric,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT llm_partner_budget_overrides_pkey PRIMARY KEY (partner_id),
  CONSTRAINT llm_partner_budget_overrides_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.llm_provider_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider text NOT NULL,
  display_name text,
  base_url text NOT NULL,
  auth_type text NOT NULL DEFAULT 'api_key'::text,
  auth_config jsonb,
  api_version text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT llm_provider_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.llm_provider_models (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_account_id uuid NOT NULL,
  model text NOT NULL,
  display_label text,
  hint text,
  badges jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(badges) = 'array'::text),
  recommended boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 100,
  temperature numeric,
  max_tokens integer,
  input_cost_usd_per_1k numeric,
  output_cost_usd_per_1k numeric,
  cache_read_cost_usd_per_1k numeric,
  cache_write_cost_usd_per_1k numeric,
  reasoning_cost_usd_per_1k numeric,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT llm_provider_models_pkey PRIMARY KEY (id),
  CONSTRAINT llm_provider_models_provider_account_id_fkey FOREIGN KEY (provider_account_id) REFERENCES public.llm_provider_accounts(id)
);
CREATE TABLE public.llm_provider_price_observations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  provider text NOT NULL,
  model text NOT NULL,
  source_kind text NOT NULL DEFAULT 'provider_web'::text,
  source_url text,
  fetched_at timestamp with time zone NOT NULL DEFAULT now(),
  input_cost_eur_per_1k numeric,
  output_cost_eur_per_1k numeric,
  parse_confidence numeric,
  parse_status text NOT NULL DEFAULT 'unknown'::text,
  parse_message text,
  raw_excerpt text,
  is_applied boolean NOT NULL DEFAULT false,
  applied_at timestamp with time zone,
  CONSTRAINT llm_provider_price_observations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.llm_usage_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  partner_id uuid,
  route_name text NOT NULL,
  mode text NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  estimated_cost_eur numeric,
  status text NOT NULL DEFAULT 'ok'::text,
  error_code text,
  provider_account_id uuid,
  provider_model_id uuid,
  billing_currency text NOT NULL DEFAULT 'USD'::text CHECK (char_length(TRIM(BOTH FROM billing_currency)) > 0),
  fx_rate_usd_to_eur numeric,
  input_cost_usd_per_1k_snapshot numeric,
  output_cost_usd_per_1k_snapshot numeric,
  cache_read_cost_usd_per_1k_snapshot numeric,
  cache_write_cost_usd_per_1k_snapshot numeric,
  reasoning_cost_usd_per_1k_snapshot numeric,
  estimated_cost_usd numeric,
  cached_tokens integer,
  cache_read_tokens integer,
  cache_write_tokens integer,
  reasoning_tokens integer,
  request_id text,
  raw_usage_json jsonb,
  CONSTRAINT llm_usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT llm_usage_events_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT llm_usage_events_provider_account_id_fkey FOREIGN KEY (provider_account_id) REFERENCES public.llm_provider_accounts(id),
  CONSTRAINT llm_usage_events_provider_model_id_fkey FOREIGN KEY (provider_model_id) REFERENCES public.llm_provider_models(id)
);
CREATE TABLE public.market_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  area_id text,
  reference_date date NOT NULL,
  avg_price_sqm_house double precision,
  avg_price_sqm_apartment double precision,
  purchase_yield double precision,
  vacancy_rate double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT market_data_pkey PRIMARY KEY (id),
  CONSTRAINT market_data_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.market_explanation_static_text_entries (
  key text NOT NULL,
  locale text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'internal'::text, 'live'::text])),
  value_text text NOT NULL DEFAULT ''::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT market_explanation_static_text_entries_pkey PRIMARY KEY (key, locale)
);
CREATE TABLE public.market_explanation_static_text_i18n_meta (
  key text NOT NULL,
  locale text NOT NULL,
  source_locale text NOT NULL DEFAULT 'de'::text,
  source_snapshot_hash text,
  source_updated_at timestamp with time zone,
  translation_origin text NOT NULL DEFAULT 'manual'::text CHECK (translation_origin = ANY (ARRAY['manual'::text, 'ai'::text, 'sync_copy_all'::text, 'sync_fill_missing'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT market_explanation_static_text_i18n_meta_pkey PRIMARY KEY (key, locale)
);
CREATE TABLE public.network_company_profiles (
  content_item_id uuid NOT NULL,
  company_name text NOT NULL,
  industry_type text,
  service_region text,
  address_json jsonb,
  contact_json jsonb,
  CONSTRAINT network_company_profiles_pkey PRIMARY KEY (content_item_id),
  CONSTRAINT network_company_profiles_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id)
);
CREATE TABLE public.network_content_i18n (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_item_id uuid NOT NULL,
  locale text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['machine_generated'::text, 'reviewed'::text, 'edited'::text, 'stale'::text])),
  translated_title text,
  translated_summary text,
  translated_body_md text,
  source_snapshot_hash text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_content_i18n_pkey PRIMARY KEY (id),
  CONSTRAINT network_content_i18n_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id)
);
CREATE TABLE public.network_content_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  portal_partner_id uuid NOT NULL,
  network_partner_id uuid NOT NULL,
  booking_id uuid NOT NULL,
  area_id text NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['company_profile'::text, 'property_offer'::text, 'property_request'::text])),
  source_type text NOT NULL DEFAULT 'manual'::text CHECK (source_type = ANY (ARRAY['manual'::text, 'api'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_review'::text, 'approved'::text, 'live'::text, 'paused'::text, 'rejected'::text, 'expired'::text])),
  slug text NOT NULL,
  title text NOT NULL,
  summary text,
  body_md text,
  cta_label text,
  cta_url text,
  primary_locale text NOT NULL DEFAULT 'de'::text,
  published_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_content_items_pkey PRIMARY KEY (id),
  CONSTRAINT network_content_items_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id),
  CONSTRAINT network_content_items_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id),
  CONSTRAINT network_content_items_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.network_partner_bookings(id),
  CONSTRAINT network_content_items_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.network_content_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_item_id uuid NOT NULL,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['logo'::text, 'hero'::text, 'gallery'::text, 'document'::text])),
  url text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_content_media_pkey PRIMARY KEY (id),
  CONSTRAINT network_content_media_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id)
);
CREATE TABLE public.network_content_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content_item_id uuid NOT NULL,
  review_status text NOT NULL DEFAULT 'pending'::text CHECK (review_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by_user_id uuid,
  review_note text,
  reviewed_at timestamp with time zone,
  CONSTRAINT network_content_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT network_content_reviews_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id),
  CONSTRAINT network_content_reviews_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.network_partner_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  portal_partner_id uuid NOT NULL,
  network_partner_id uuid NOT NULL,
  area_id text NOT NULL,
  placement_code text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'active'::text, 'paused'::text, 'cancelled'::text, 'expired'::text])),
  starts_at date NOT NULL,
  ends_at date,
  monthly_price_eur numeric NOT NULL CHECK (monthly_price_eur >= 0::numeric),
  portal_fee_eur numeric NOT NULL CHECK (portal_fee_eur >= 0::numeric),
  billing_cycle_day integer NOT NULL CHECK (billing_cycle_day >= 1 AND billing_cycle_day <= 28),
  required_locales jsonb NOT NULL DEFAULT '["de"]'::jsonb CHECK (jsonb_typeof(required_locales) = 'array'::text),
  ai_billing_mode text NOT NULL DEFAULT 'included'::text CHECK (ai_billing_mode = ANY (ARRAY['included'::text, 'credit_based'::text, 'blocked'::text])),
  ai_monthly_budget_eur numeric NOT NULL DEFAULT 0 CHECK (ai_monthly_budget_eur >= 0::numeric),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_partner_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT network_partner_bookings_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id),
  CONSTRAINT network_partner_bookings_placement_code_fkey FOREIGN KEY (placement_code) REFERENCES public.placement_catalog(code),
  CONSTRAINT network_partner_bookings_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id),
  CONSTRAINT network_partner_bookings_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id)
);
CREATE TABLE public.network_partner_integration_sync_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  integration_id uuid NOT NULL,
  portal_partner_id uuid NOT NULL,
  network_partner_id uuid NOT NULL,
  run_kind text NOT NULL CHECK (run_kind = ANY (ARRAY['test'::text, 'preview'::text, 'sync'::text])),
  run_mode text NOT NULL CHECK (run_mode = ANY (ARRAY['guarded'::text, 'full'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['running'::text, 'ok'::text, 'warning'::text, 'error'::text])),
  trace_id text,
  summary jsonb,
  diagnostics jsonb,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_partner_integration_sync_runs_pkey PRIMARY KEY (id),
  CONSTRAINT network_partner_integration_sync_runs_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id),
  CONSTRAINT network_partner_integration_sync_runs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.network_partner_integrations(id),
  CONSTRAINT network_partner_integration_sync_runs_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id)
);
CREATE TABLE public.network_partner_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  portal_partner_id uuid NOT NULL,
  network_partner_id uuid NOT NULL,
  kind text NOT NULL DEFAULT 'crm'::text CHECK (kind = 'crm'::text),
  provider text NOT NULL CHECK (provider = ANY (ARRAY['propstack'::text, 'onoffice'::text])),
  base_url text,
  auth_type text,
  auth_config jsonb,
  detail_url_template text,
  is_active boolean NOT NULL DEFAULT true,
  settings jsonb,
  last_test_at timestamp with time zone,
  last_preview_sync_at timestamp with time zone,
  last_sync_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_partner_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT network_partner_integrations_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id),
  CONSTRAINT network_partner_integrations_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id)
);
CREATE TABLE public.network_partner_invoice_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  portal_partner_id uuid NOT NULL,
  network_partner_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  gross_amount_eur numeric NOT NULL CHECK (gross_amount_eur >= 0::numeric),
  portal_fee_eur numeric NOT NULL CHECK (portal_fee_eur >= 0::numeric),
  partner_net_eur numeric NOT NULL CHECK (partner_net_eur >= 0::numeric),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'paid'::text, 'overdue'::text, 'cancelled'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_partner_invoice_lines_pkey PRIMARY KEY (id),
  CONSTRAINT network_partner_invoice_lines_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.network_partner_bookings(id),
  CONSTRAINT network_partner_invoice_lines_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id),
  CONSTRAINT network_partner_invoice_lines_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id)
);
CREATE TABLE public.network_partner_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  network_partner_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['network_owner'::text, 'network_editor'::text, 'network_billing'::text])),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_partner_users_pkey PRIMARY KEY (id),
  CONSTRAINT network_partner_users_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id),
  CONSTRAINT network_partner_users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.network_partners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  portal_partner_id uuid NOT NULL,
  company_name text NOT NULL,
  legal_name text,
  contact_email text NOT NULL,
  contact_phone text,
  website_url text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'paused'::text, 'inactive'::text])),
  managed_editing_enabled boolean NOT NULL DEFAULT false,
  llm_partner_managed_allowed boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT network_partners_pkey PRIMARY KEY (id),
  CONSTRAINT network_partners_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.network_property_offers (
  content_item_id uuid NOT NULL,
  external_id text,
  marketing_type text,
  property_type text,
  location_label text,
  price numeric,
  living_area numeric,
  plot_area numeric,
  rooms numeric,
  facts_json jsonb,
  CONSTRAINT network_property_offers_pkey PRIMARY KEY (content_item_id),
  CONSTRAINT network_property_offers_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id)
);
CREATE TABLE public.network_property_requests (
  content_item_id uuid NOT NULL,
  external_id text,
  request_type text,
  search_region text,
  budget_min numeric,
  budget_max numeric,
  area_min numeric,
  area_max numeric,
  facts_json jsonb,
  CONSTRAINT network_property_requests_pkey PRIMARY KEY (content_item_id),
  CONSTRAINT network_property_requests_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id)
);
CREATE TABLE public.partner_ai_credit_ledgers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  period_key text NOT NULL,
  opening_balance_eur numeric NOT NULL DEFAULT 0,
  credits_added_eur numeric NOT NULL DEFAULT 0,
  credits_used_eur numeric NOT NULL DEFAULT 0,
  closing_balance_eur numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_ai_credit_ledgers_pkey PRIMARY KEY (id),
  CONSTRAINT partner_ai_credit_ledgers_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_ai_usage_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text,
  network_partner_id uuid,
  content_item_id uuid,
  feature text NOT NULL CHECK (feature = ANY (ARRAY['content_optimize'::text, 'content_translate'::text, 'seo_meta_generate'::text])),
  locale text,
  billing_mode text NOT NULL CHECK (billing_mode = ANY (ARRAY['included'::text, 'credit_based'::text, 'blocked'::text])),
  prompt_tokens integer NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
  completion_tokens integer NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
  estimated_cost_eur numeric NOT NULL DEFAULT 0 CHECK (estimated_cost_eur >= 0::numeric),
  credit_delta_eur numeric NOT NULL DEFAULT 0 CHECK (credit_delta_eur >= 0::numeric),
  status text NOT NULL DEFAULT 'ok'::text CHECK (status = ANY (ARRAY['ok'::text, 'blocked'::text, 'error'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_ai_usage_events_pkey PRIMARY KEY (id),
  CONSTRAINT partner_ai_usage_events_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_ai_usage_events_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id),
  CONSTRAINT partner_ai_usage_events_network_partner_id_fkey FOREIGN KEY (network_partner_id) REFERENCES public.network_partners(id),
  CONSTRAINT partner_ai_usage_events_content_item_id_fkey FOREIGN KEY (content_item_id) REFERENCES public.network_content_items(id)
);
CREATE TABLE public.partner_area_generated_texts (
  partner_id text NOT NULL,
  area_id text NOT NULL,
  scope text NOT NULL CHECK (scope = ANY (ARRAY['kreis'::text, 'ortslage'::text])),
  section_key text NOT NULL,
  value_text text NOT NULL DEFAULT ''::text,
  source_signature text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_area_generated_texts_pkey PRIMARY KEY (partner_id, area_id, scope, section_key)
);
CREATE TABLE public.partner_area_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text NOT NULL,
  placement_code text NOT NULL,
  slot_limit integer NOT NULL CHECK (slot_limit > 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_area_inventory_pkey PRIMARY KEY (id),
  CONSTRAINT partner_area_inventory_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_area_inventory_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id),
  CONSTRAINT partner_area_inventory_placement_code_fkey FOREIGN KEY (placement_code) REFERENCES public.placement_catalog(code)
);
CREATE TABLE public.partner_area_map (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL,
  area_id text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  activation_status text NOT NULL DEFAULT 'assigned'::text,
  mandatory_checked_at timestamp with time zone,
  mandatory_missing_keys jsonb,
  partner_submitted_at timestamp with time zone,
  is_public_live boolean NOT NULL DEFAULT false,
  admin_review_note text,
  partner_preview_signoff_at timestamp with time zone,
  reference_visibility_mode text NOT NULL DEFAULT 'partner_wide'::text CHECK (reference_visibility_mode = ANY (ARRAY['partner_wide'::text, 'strict_local'::text])),
  CONSTRAINT partner_area_map_pkey PRIMARY KEY (id),
  CONSTRAINT partner_area_map_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES public.partners(id),
  CONSTRAINT partner_area_map_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.partner_area_runtime_states (
  partner_id text NOT NULL,
  area_id text NOT NULL,
  scope text NOT NULL CHECK (scope = ANY (ARRAY['kreis'::text, 'ortslage'::text])),
  factors_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  data_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  textgen_inputs_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  helpers_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  rebuilt_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_area_runtime_states_pkey PRIMARY KEY (partner_id, area_id, scope)
);
CREATE TABLE public.partner_billing_settings (
  partner_id uuid NOT NULL,
  portal_base_price_eur numeric CHECK (portal_base_price_eur IS NULL OR portal_base_price_eur >= 0::numeric),
  portal_ortslage_price_eur numeric CHECK (portal_ortslage_price_eur IS NULL OR portal_ortslage_price_eur >= 0::numeric),
  portal_export_ortslage_price_eur numeric CHECK (portal_export_ortslage_price_eur IS NULL OR portal_export_ortslage_price_eur >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_billing_settings_pkey PRIMARY KEY (partner_id),
  CONSTRAINT partner_billing_settings_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_blog_post_i18n (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  post_id uuid NOT NULL,
  area_id text NOT NULL,
  target_locale text NOT NULL CHECK (target_locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  translated_headline text,
  translated_subline text,
  translated_body_md text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'needs_review'::text])),
  source_snapshot_hash text,
  source_last_updated timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_blog_post_i18n_pkey PRIMARY KEY (id),
  CONSTRAINT partner_blog_post_i18n_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES auth.users(id),
  CONSTRAINT partner_blog_post_i18n_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.partner_blog_posts(id)
);
CREATE TABLE public.partner_blog_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text NOT NULL,
  area_name text,
  bundesland_slug text,
  kreis_slug text,
  headline text NOT NULL,
  subline text,
  body_md text NOT NULL,
  author_name text,
  author_image_url text,
  source_individual_01 text,
  source_individual_02 text,
  source_zitat text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'draft'::text,
  CONSTRAINT partner_blog_posts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.partner_feature_overrides (
  partner_id uuid NOT NULL,
  feature_code text NOT NULL,
  is_enabled boolean,
  monthly_price_eur numeric CHECK (monthly_price_eur IS NULL OR monthly_price_eur >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_feature_overrides_pkey PRIMARY KEY (partner_id, feature_code),
  CONSTRAINT partner_feature_overrides_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_feature_overrides_feature_code_fkey FOREIGN KEY (feature_code) REFERENCES public.billing_feature_catalog(code)
);
CREATE TABLE public.partner_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  kind text NOT NULL,
  provider text NOT NULL,
  base_url text,
  auth_type text,
  auth_config jsonb,
  detail_url_template text,
  is_active boolean DEFAULT true,
  settings jsonb,
  last_sync_at timestamp with time zone,
  CONSTRAINT partner_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT partner_integrations_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.crm_raw_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  title text,
  status text,
  source_updated_at timestamp with time zone,
  normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sync_status text NOT NULL DEFAULT 'ok'::text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_raw_offers_pkey PRIMARY KEY (id),
  CONSTRAINT crm_raw_offers_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_local_site_texts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text NOT NULL,
  section_key text NOT NULL,
  text_type text,
  raw_content text,
  optimized_content text,
  status text NOT NULL DEFAULT 'draft'::text,
  last_updated timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_local_site_texts_pkey PRIMARY KEY (id),
  CONSTRAINT partner_local_site_texts_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_local_site_texts_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.partner_marketing_texts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text NOT NULL,
  section_key text NOT NULL,
  text_type text,
  raw_content text,
  optimized_content text,
  status text DEFAULT 'draft'::text,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT partner_marketing_texts_pkey PRIMARY KEY (id),
  CONSTRAINT partner_marketing_texts_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_marketing_texts_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.partner_offer_area_targets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  offer_id uuid NOT NULL,
  area_id text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  match_source text NOT NULL,
  match_confidence text NOT NULL CHECK (match_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  score numeric,
  matched_zip_code text,
  matched_city text,
  matched_region text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_offer_area_targets_pkey PRIMARY KEY (id),
  CONSTRAINT partner_offer_area_targets_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.partner_property_offers(id),
  CONSTRAINT partner_offer_area_targets_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id),
  CONSTRAINT partner_offer_area_targets_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_property_offer_i18n (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  offer_id uuid NOT NULL,
  area_id text,
  source text NOT NULL,
  external_id text NOT NULL,
  target_locale text NOT NULL CHECK (target_locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  translated_seo_title text,
  translated_seo_description text,
  translated_seo_h1 text,
  translated_short_description text,
  translated_long_description text,
  translated_location_text text,
  translated_features_text text,
  translated_highlights ARRAY NOT NULL DEFAULT '{}'::text[],
  translated_image_alt_texts ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'needs_review'::text])),
  source_snapshot_hash text,
  source_last_updated timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  translated_answer_summary text,
  translated_location_summary text,
  translated_target_audience text,
  CONSTRAINT partner_property_offer_i18n_pkey PRIMARY KEY (id),
  CONSTRAINT partner_property_offer_i18n_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES auth.users(id),
  CONSTRAINT partner_property_offer_i18n_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.partner_property_offers(id)
);
CREATE TABLE public.partner_property_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text,
  offer_type text NOT NULL CHECK (offer_type = ANY (ARRAY['kauf'::text, 'miete'::text])),
  object_type text NOT NULL CHECK (object_type = ANY (ARRAY['haus'::text, 'wohnung'::text])),
  title text,
  price numeric,
  rent numeric,
  area_sqm numeric,
  rooms numeric,
  address text,
  image_url text,
  detail_url text,
  is_top boolean DEFAULT false,
  marketing_flags jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(marketing_flags) = 'array'::text),
  updated_at timestamp with time zone DEFAULT now(),
  raw jsonb,
  source text,
  external_id text,
  CONSTRAINT partner_property_offers_pkey PRIMARY KEY (id),
  CONSTRAINT partner_property_offers_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_property_offers_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.partner_property_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  is_active_override boolean,
  is_top_override boolean,
  seo_title text,
  seo_description text,
  seo_h1 text,
  short_description text,
  long_description text,
  location_text text,
  features_text text,
  highlights jsonb,
  image_alt_texts jsonb,
  request_image_catalog_id text,
  status text DEFAULT 'draft'::text,
  last_updated timestamp with time zone DEFAULT now(),
  answer_summary text,
  location_summary text,
  target_audience text,
  CONSTRAINT partner_property_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT partner_property_overrides_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_reference_i18n (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  reference_id uuid NOT NULL,
  area_id text NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  target_locale text NOT NULL CHECK (target_locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  translated_seo_title text,
  translated_seo_description text,
  translated_seo_h1 text,
  translated_short_description text,
  translated_long_description text,
  translated_location_text text,
  translated_features_text text,
  translated_highlights ARRAY NOT NULL DEFAULT '{}'::text[],
  translated_image_alt_texts ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'needs_review'::text])),
  source_snapshot_hash text,
  source_last_updated timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_reference_i18n_pkey PRIMARY KEY (id),
  CONSTRAINT partner_reference_i18n_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES auth.users(id),
  CONSTRAINT partner_reference_i18n_reference_id_fkey FOREIGN KEY (reference_id) REFERENCES public.partner_references(id)
);
CREATE TABLE public.partner_reference_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  is_active_override boolean,
  seo_title text,
  seo_description text,
  seo_h1 text,
  short_description text,
  long_description text,
  location_text text,
  features_text text,
  image_url text,
  highlights jsonb,
  image_alt_texts jsonb,
  status text DEFAULT 'draft'::text,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT partner_reference_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT partner_reference_overrides_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  title text,
  status text,
  source_updated_at timestamp with time zone,
  normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sync_status text NOT NULL DEFAULT 'ok'::text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source text,
  lifecycle_status text NOT NULL DEFAULT 'active'::text CHECK (lifecycle_status = ANY (ARRAY['active'::text, 'stale'::text, 'expired'::text, 'hidden'::text, 'draft'::text])),
  is_live boolean NOT NULL DEFAULT true,
  canonical_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  owner_account_id uuid,
  publisher_account_id uuid,
  CONSTRAINT partner_references_pkey PRIMARY KEY (id),
  CONSTRAINT partner_references_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_references_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES public.partners(id),
  CONSTRAINT partner_references_publisher_account_id_fkey FOREIGN KEY (publisher_account_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_request_i18n (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  request_id uuid NOT NULL,
  area_id text NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  target_locale text NOT NULL CHECK (target_locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  translated_seo_title text,
  translated_seo_description text,
  translated_seo_h1 text,
  translated_short_description text,
  translated_long_description text,
  translated_location_text text,
  translated_features_text text,
  translated_highlights ARRAY NOT NULL DEFAULT '{}'::text[],
  translated_image_alt_texts ARRAY NOT NULL DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'needs_review'::text])),
  source_snapshot_hash text,
  source_last_updated timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_request_i18n_pkey PRIMARY KEY (id),
  CONSTRAINT partner_request_i18n_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES auth.users(id),
  CONSTRAINT partner_request_i18n_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.partner_requests(id)
);
CREATE TABLE public.partner_request_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  is_active_override boolean,
  seo_title text,
  seo_description text,
  seo_h1 text,
  short_description text,
  long_description text,
  location_text text,
  features_text text,
  highlights jsonb,
  image_alt_texts jsonb,
  request_image_catalog_id text,
  status text DEFAULT 'draft'::text,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT partner_request_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT partner_request_overrides_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  title text,
  status text,
  source_updated_at timestamp with time zone,
  normalized_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  sync_status text NOT NULL DEFAULT 'ok'::text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source text,
  lifecycle_status text NOT NULL DEFAULT 'active'::text CHECK (lifecycle_status = ANY (ARRAY['active'::text, 'stale'::text, 'expired'::text, 'hidden'::text, 'draft'::text])),
  is_live boolean NOT NULL DEFAULT true,
  canonical_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  owner_account_id uuid,
  publisher_account_id uuid,
  CONSTRAINT partner_requests_pkey PRIMARY KEY (id),
  CONSTRAINT partner_requests_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_requests_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES public.partners(id),
  CONSTRAINT partner_requests_publisher_account_id_fkey FOREIGN KEY (publisher_account_id) REFERENCES public.partners(id)
);
CREATE TABLE public.partner_texts_i18n (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text NOT NULL,
  section_key text NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['portal'::text, 'local_site'::text, 'marketing'::text])),
  target_locale text NOT NULL CHECK (target_locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  translated_content text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'needs_review'::text])),
  source_snapshot_hash text,
  source_last_updated timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_texts_i18n_pkey PRIMARY KEY (id),
  CONSTRAINT partner_texts_i18n_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.partner_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['partner_owner'::text, 'partner_manager'::text, 'partner_billing'::text])),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partner_users_pkey PRIMARY KEY (id),
  CONSTRAINT partner_users_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT partner_users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT auth.uid(),
  company_name text NOT NULL,
  website_url text,
  created_at timestamp with time zone DEFAULT now(),
  contact_email text,
  is_active boolean NOT NULL DEFAULT true,
  contact_first_name text NOT NULL,
  contact_last_name text NOT NULL,
  llm_partner_managed_allowed boolean NOT NULL DEFAULT false,
  llm_mode_default text NOT NULL DEFAULT 'central_managed'::text,
  is_system_default boolean NOT NULL DEFAULT false,
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.placement_catalog (
  code text NOT NULL,
  label text NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['company_profile'::text, 'property_offer'::text, 'property_request'::text])),
  billing_mode text NOT NULL CHECK (billing_mode = 'monthly_fixed'::text),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT placement_catalog_pkey PRIMARY KEY (code)
);
CREATE TABLE public.portal_content_entries (
  page_key text NOT NULL,
  section_key text NOT NULL,
  locale text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'internal'::text, 'live'::text])),
  fields_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portal_content_entries_pkey PRIMARY KEY (page_key, section_key, locale)
);
CREATE TABLE public.portal_content_i18n_meta (
  page_key text NOT NULL,
  section_key text NOT NULL,
  locale text NOT NULL,
  source_locale text NOT NULL DEFAULT 'de'::text,
  source_snapshot_hash text,
  source_updated_at timestamp with time zone,
  translation_origin text NOT NULL DEFAULT 'manual'::text CHECK (translation_origin = ANY (ARRAY['manual'::text, 'ai'::text, 'sync_copy_all'::text, 'sync_fill_missing'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portal_content_i18n_meta_pkey PRIMARY KEY (page_key, section_key, locale)
);
CREATE TABLE public.portal_locale_config (
  locale text NOT NULL,
  status text NOT NULL DEFAULT 'planned'::text CHECK (status = ANY (ARRAY['planned'::text, 'internal'::text, 'live'::text])),
  partner_bookable boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT false,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  label_native text,
  label_de text,
  bcp47_tag text,
  fallback_locale text NOT NULL DEFAULT 'de'::text,
  text_direction text NOT NULL DEFAULT 'ltr'::text CHECK (text_direction = ANY (ARRAY['ltr'::text, 'rtl'::text])),
  number_locale text,
  date_locale text,
  currency_code text NOT NULL DEFAULT 'EUR'::text,
  billing_feature_code text,
  CONSTRAINT portal_locale_config_pkey PRIMARY KEY (locale)
);
CREATE TABLE public.portal_partner_settlement_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_line_id uuid NOT NULL,
  portal_partner_id uuid NOT NULL,
  gross_amount_eur numeric NOT NULL CHECK (gross_amount_eur >= 0::numeric),
  portal_fee_eur numeric NOT NULL CHECK (portal_fee_eur >= 0::numeric),
  partner_net_eur numeric NOT NULL CHECK (partner_net_eur >= 0::numeric),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'cleared'::text, 'held'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portal_partner_settlement_lines_pkey PRIMARY KEY (id),
  CONSTRAINT portal_partner_settlement_lines_invoice_line_id_fkey FOREIGN KEY (invoice_line_id) REFERENCES public.network_partner_invoice_lines(id),
  CONSTRAINT portal_partner_settlement_lines_portal_partner_id_fkey FOREIGN KEY (portal_partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.portal_system_text_entries (
  key text NOT NULL,
  locale text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'internal'::text, 'live'::text])),
  value_text text NOT NULL DEFAULT ''::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portal_system_text_entries_pkey PRIMARY KEY (key, locale)
);
CREATE TABLE public.portal_system_text_i18n_meta (
  key text NOT NULL,
  locale text NOT NULL,
  source_locale text NOT NULL DEFAULT 'de'::text,
  source_snapshot_hash text,
  source_updated_at timestamp with time zone,
  translation_origin text NOT NULL DEFAULT 'manual'::text CHECK (translation_origin = ANY (ARRAY['manual'::text, 'ai'::text, 'sync_copy_all'::text, 'sync_fill_missing'::text])),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT portal_system_text_i18n_meta_pkey PRIMARY KEY (key, locale)
);
CREATE TABLE public.public_offer_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  visible_area_id text NOT NULL,
  locale text NOT NULL CHECK (locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  offer_id uuid NOT NULL,
  source text NOT NULL,
  external_id text NOT NULL,
  offer_type text NOT NULL,
  object_type text,
  title text,
  seo_title text,
  seo_description text,
  seo_h1 text,
  short_description text,
  long_description text,
  location_text text,
  features_text text,
  highlights jsonb NOT NULL DEFAULT '[]'::jsonb,
  image_alt_texts jsonb NOT NULL DEFAULT '[]'::jsonb,
  price numeric,
  rent numeric,
  area_sqm numeric,
  rooms numeric,
  address text,
  image_url text,
  detail_url text,
  is_top boolean NOT NULL DEFAULT false,
  marketing_flags jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(marketing_flags) = 'array'::text),
  is_live boolean NOT NULL DEFAULT true,
  source_updated_at timestamp with time zone,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  answer_summary text,
  location_summary text,
  target_audience text,
  CONSTRAINT public_offer_entries_pkey PRIMARY KEY (id),
  CONSTRAINT public_offer_entries_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.partner_property_offers(id),
  CONSTRAINT public_offer_entries_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT public_offer_entries_visible_area_id_fkey FOREIGN KEY (visible_area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.public_reference_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  visible_area_id text NOT NULL,
  locale text NOT NULL CHECK (locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  reference_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  title text,
  seo_title text,
  seo_description text,
  seo_h1 text,
  short_description text,
  long_description text,
  location_text text,
  features_text text,
  highlights jsonb NOT NULL DEFAULT '[]'::jsonb,
  image_alt_texts jsonb NOT NULL DEFAULT '[]'::jsonb,
  description text,
  image_url text,
  city text,
  district text,
  is_live boolean NOT NULL DEFAULT true,
  source_updated_at timestamp with time zone,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT public_reference_entries_pkey PRIMARY KEY (id),
  CONSTRAINT public_reference_entries_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT public_reference_entries_visible_area_id_fkey FOREIGN KEY (visible_area_id) REFERENCES public.areas(id),
  CONSTRAINT public_reference_entries_reference_id_fkey FOREIGN KEY (reference_id) REFERENCES public.partner_references(id)
);
CREATE TABLE public.public_request_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  visible_area_id text NOT NULL,
  locale text NOT NULL CHECK (locale ~ '^[a-z]{2}(-[a-z]{2})?$'::text),
  request_id uuid NOT NULL,
  provider text NOT NULL,
  external_id text NOT NULL,
  request_type text NOT NULL,
  object_type text,
  object_subtype text,
  title text,
  seo_title text,
  seo_description text,
  seo_h1 text,
  short_description text,
  long_description text,
  location_text text,
  features_text text,
  highlights jsonb NOT NULL DEFAULT '[]'::jsonb,
  image_alt_texts jsonb NOT NULL DEFAULT '[]'::jsonb,
  request_image_catalog_id text,
  min_rooms numeric,
  max_rooms numeric,
  min_area_sqm numeric,
  max_area_sqm numeric,
  min_living_area_sqm numeric,
  max_living_area_sqm numeric,
  min_price numeric,
  max_price numeric,
  radius_km numeric,
  region_targets jsonb NOT NULL DEFAULT '[]'::jsonb,
  region_target_keys jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_live boolean NOT NULL DEFAULT true,
  source_updated_at timestamp with time zone,
  published_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT public_request_entries_pkey PRIMARY KEY (id),
  CONSTRAINT public_request_entries_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT public_request_entries_visible_area_id_fkey FOREIGN KEY (visible_area_id) REFERENCES public.areas(id),
  CONSTRAINT public_request_entries_request_id_fkey FOREIGN KEY (request_id) REFERENCES public.partner_requests(id)
);
CREATE TABLE public.report_texts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  partner_id uuid NOT NULL,
  area_id text NOT NULL,
  section_key text NOT NULL,
  text_type USER-DEFINED NOT NULL,
  raw_content text,
  optimized_content text,
  status text DEFAULT 'approved'::text,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT report_texts_pkey PRIMARY KEY (id),
  CONSTRAINT report_texts_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT report_texts_area_id_fkey FOREIGN KEY (area_id) REFERENCES public.areas(id)
);
CREATE TABLE public.security_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_user_id uuid,
  actor_role text NOT NULL,
  event_type text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  payload jsonb,
  ip text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_rate_limits (
  key_hash text NOT NULL,
  count integer NOT NULL DEFAULT 0,
  reset_at timestamp with time zone NOT NULL,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT security_rate_limits_pkey PRIMARY KEY (key_hash)
);
