import { getMandatoryMediaLabel, isMandatoryMediaKey } from "@/lib/mandatory-media";

const TEXT_KEY_LABELS: Record<string, string> = {
  berater_name: "Name",
  berater_email: "E-Mail",
  berater_telefon_fest: "Telefon (Festnetz)",
  berater_telefon_mobil: "Telefon (Mobil)",
  berater_adresse_strasse: "Straße",
  berater_adresse_hnr: "Hausnummer",
  berater_adresse_plz: "PLZ",
  berater_adresse_ort: "Ort",
  berater_beschreibung: "Kurz-Bio / Beschreibung",
  berater_ausbildung: "Qualifikationen / Ausbildung",
  makler_name: "Firma / Name",
  makler_email: "E-Mail",
  makler_telefon_fest: "Telefon (Festnetz)",
  makler_telefon_mobil: "Telefon (Mobil)",
  makler_adresse_strasse: "Straße",
  makler_adresse_hnr: "Hausnummer",
  makler_adresse_plz: "PLZ",
  makler_adresse_ort: "Ort",
  makler_empfehlung: "Intro",
  makler_beschreibung: "Leistungsbeschreibung",
  makler_benefits: "Vorteile / Benefits",
  makler_provision: "Provisionshinweis",
  immobilienmarkt_allgemein: "Berater-Ansprache (Teaser)",
  immobilienmarkt_standort_teaser: "Standort Teaser",
  immobilienmarkt_individuell_01: "Experteneinschätzung Text 01",
  immobilienmarkt_zitat: "Experten-Zitat",
  immobilienmarkt_individuell_02: "Experteneinschätzung Text 02",
  immobilienmarkt_beschreibung_01: "Marktanalyse Teil 1",
  immobilienmarkt_beschreibung_02: "Marktanalyse Teil 2",
  immobilienmarkt_besonderheiten: "Kaufnebenkosten Info",
  immobilienmarkt_maklerempfehlung: "Maklerempfehlung",
  immobilienpreise_intro: "Einleitung Preise",
  ueberschrift_immobilienpreise_haus: "H2 Überschrift Haus",
  immobilienpreise_haus_intro: "Intro Hauspreise",
  immobilienpreise_haus_allgemein: "Hauspreise Allgemein",
  immobilienpreise_haus_lage: "Einfluss der Lage",
  immobilienpreise_haus_haustypen: "Preise nach Haustypen",
  immobilienpreise_haus_preisentwicklung: "Preisentwicklung Haus",
  ueberschrift_immobilienpreise_wohnung: "H2 Überschrift Wohnung",
  immobilienpreise_wohnung_intro: "Intro Wohnungspreise",
  immobilienpreise_wohnung_allgemein: "Wohnungspreise Allgemein",
  immobilienpreise_wohnung_lage: "Lagefaktoren Wohnung",
  immobilienpreise_wohnung_preisentwicklung: "Preisentwicklung Wohnung",
  immobilienpreise_wohnung_nach_flaechen_und_zimmern: "Preise nach Zimmer/Fläche",
  mietpreise_intro: "Einleitung Mieten",
  mietpreise_allgemein: "Mietmarkt Übersicht",
  ueberschrift_mietpreise_wohnung: "H2 Mietpreise Wohnung",
  mietpreise_wohnung_allgemein: "Wohnungsmieten Allgemein",
  mietpreise_wohnung_nach_flaechen_und_zimmern: "Mieten nach Segmenten",
  mietpreise_wohnung_preisentwicklung: "Preisentwicklung Miete (ETW)",
  ueberschrift_mietpreise_haus: "H2 Mietpreise Haus",
  mietpreise_haus_allgemein: "Hausmieten Allgemein",
  mietpreise_haus_preisentwicklung: "Preisentwicklung Miete (Haus)",
  mietrendite_intro: "Einleitung Rendite",
  mietrendite_kaufpreisfaktor: "Kaufpreisfaktor Info",
  ueberschrift_mietrendite_bruttomietrendite: "H2 Bruttomietrendite",
  mietrendite_allgemein: "Rendite Analyse",
  mietrendite_hinweis: "Wichtiger Hinweis",
  mietrendite_etw: "Rendite ETW",
  mietrendite_efh: "Rendite EFH",
  mietrendite_mfh: "Rendite MFH",
  wohnmarktsituation_intro: "Einleitung Markt",
  wohnmarktsituation_wohnraumnachfrage: "Nachfrage Introtext",
  wohnmarktsituation_wohnraumangebot_intro: "Wohnraumangebot Introtext",
  wohnmarktsituation_wohnungsbestand_intro: "Wohnungsbestand Introtext",
  wohnmarktsituation_baufertigstellungen_intro: "Baufertigstellungen Introtext",
  wohnmarktsituation_baugenehmigungen_intro: "Baugenehmigungen Introtext",
  wohnmarktsituation_bautaetigkeit_intro: "Bautätigkeit Introtext",
  wohnmarktsituation_natuerlicher_saldo_intro: "Natürlicher Saldo Introtext",
  wohnmarktsituation_wanderungssaldo_intro: "Wanderungssaldo Introtext",
  wohnmarktsituation_jugendquotient_altenquotient_intro: "Jugend-/Altenquotient Introtext",
  ueberschrift_wohnmarktsituation_wohnraumnachfrage_individuell: "H2 Nachfrage individuell",
  wohnmarktsituation_allgemein: "Nachfrage Analyse",
  wohnmarktsituation_bevoelkerungsentwicklung: "Bevölkerung",
  wohnmarktsituation_haushalte: "Haushalte",
  wohnmarktsituation_natuerlicher_saldo: "Nat. Saldo Daten",
  wohnmarktsituation_wanderungssaldo: "Wanderung Daten",
  wohnmarktsituation_alterstruktur: "Altersstruktur",
  wohnmarktsituation_jugendquotient_altenquotient: "Quotienten Daten",
  wohnmarktsituation_wohnungsbestand_anzahl: "Anzahl Wohnungen",
  wohnmarktsituation_wohnungsbestand_wohnflaeche: "Wohnfläche Bestand",
  wohnmarktsituation_baufertigstellungen: "Fertigstellungen Daten",
  wohnmarktsituation_baugenehmigungen: "Genehmigungen Daten",
  wohnmarktsituation_bauueberhang_baufortschritt: "Bauüberhang",
  ueberschrift_wohnlagencheck_allgemein: "H2 Wohnlagencheck",
  wohnlagencheck_allgemein: "Allgemeine Lage",
  wohnlagencheck_lage: "Detail-Lage",
  wohnlagencheck_standortfaktoren_intro: "Standortfaktoren Intro",
  ueberschrift_wohnlagencheck_faktoren: "H2 Standortfaktoren",
  wohnlagencheck_faktor_mobilitaet: "Mobilität",
  wohnlagencheck_faktor_bildung: "Bildung",
  wohnlagencheck_faktor_gesundheit: "Gesundheit",
  wohnlagencheck_faktor_nahversorgung: "Nahversorgung",
  wohnlagencheck_faktor_naherholung: "Naherholung",
  wohnlagencheck_faktor_kultur_freizeit: "Kultur & Freizeit",
  wohnlagencheck_faktor_arbeitsplatz: "Arbeitsplatz",
  wohnlagencheck_faktor_lebenserhaltungskosten: "Lebenserhaltungskosten",
  wohnlagencheck_faktor_sicherheit: "Sicherheit",
  wirtschaft_intro: "Einleitung Wirtschaft",
  wirtschaft_arbeitsmarkt: "Arbeitsmarkt Introtext",
  wirtschaft_gewerbesaldo: "Gewerbesaldo Introtext",
  wirtschaft_arbeitslosendichte: "Arbeitslosendichte Introtext",
  wirtschaft_sv_beschaeftigte_wohnort: "SvB Wohnort Introtext",
  ueberschrift_wirtschaft_individuell: "H2 Wirtschaft individuell",
  wirtschaft_bruttoinlandsprodukt: "BIP Analyse",
  wirtschaft_einkommen: "Einkommen",
  ueberschrift_arbeitsmarkt_individuell: "H2 Arbeitsmarkt individuell",
  wirtschaft_arbeitsplatzzentralitaet: "Zentralität",
  wirtschaft_pendler: "Pendlersaldo",
  wirtschaft_sv_beschaeftigte_arbeitsort: "Beschäftigte Arbeitsort",
  wirtschaft_arbeitslosigkeit: "Arbeitslosenquote",
  grundstueckspreise_intro: "Einleitung Grundstücke",
  ueberschrift_grundstueckspreise: "H2 Grundstückspreise",
  grundstueckspreise_allgemein: "Grundstückspreise Daten",
  grundstueckspreise_preisentwicklung: "Entwicklung Grundstücke",
};

export function getTextKeyLabel(key: string, fallback?: string): string {
  if (!key) return fallback ?? "";
  if (isMandatoryMediaKey(key)) return getMandatoryMediaLabel(key);
  return TEXT_KEY_LABELS[key] ?? fallback ?? key;
}
